#!/bin/sh /etc/rc.common
#==============================================================================
# Brief   : ODTONE OpenWrt Init Script
# Authors : Carlos Guimarães <cguimaraes@av.it.pt>
#------------------------------------------------------------------------------
# ODTONE - Open Dot Twenty One
#
# Copyright (C) 2009-2013 Universidade Aveiro
# Copyright (C) 2009-2013 Instituto de Telecomunicações - Pólo Aveiro
#
# This software is distributed under a license. The full license
# agreement can be found in the file LICENSE in this distribution.
# This software may not be copied, modified, sold or distributed
# other than expressed in the named license agreement.
#
# This software is distributed without any warranty.
#==============================================================================

START=43
STOP=57

boot() {
	odtone-mihf &
	sap_80211 &
}

start() {
	odtone-mihf &
	sap_80211 &
}

restart() {
	stop
	start
}

stop() {
	pkill -9 odtone
	pkill -9 sap_80211
}
